# https://epsg.io/
us_state_to_crs = { # m
    "Alabama": "EPSG:26929", # m
    "Alaska": "EPSG:3338", # m
    "Arizona": "EPSG:26949", # m
    "Arkansas": "EPSG:26952",
    "California": "EPSG:26944",
    "Colorado": "EPSG:26954",
    "Connecticut": "EPSG:26956",
    "Delaware": "EPSG:26957",
    "Florida": "EPSG:26958",
    "Georgia": "EPSG:26966",
    "Hawaii": "EPSG:26961",
    "Idaho": "EPSG:26969",
    "Illinois": "EPSG:26971",
    "Indiana": "EPSG:26973",
    "Iowa": "EPSG:26976",
    "Kansas": "EPSG:26978",
    "Kentucky": "EPSG:26980",
    "Louisiana": "EPSG:26982",
    "Maine": "EPSG:26983",
    "Maryland": "EPSG:26985",
    "Massachusetts": "EPSG:26987",
    "Michigan": "EPSG:26989",
    "Minnesota": "EPSG:26992",
    "Mississippi": "EPSG:26994",
    "Missouri": "EPSG:26997",
    "Montana": "EPSG:32100",
    "Nebraska": "EPSG:32104",
    "Nevada": "EPSG:32108",
    "New Hampshire": "EPSG:32110",
    "New Jersey": "EPSG:32111",
    "New Mexico": "EPSG:32113",
    "New York": "EPSG:32118",
    "North Carolina": "EPSG:32119",
    "North Dakota": "EPSG:32121",
    "Ohio": "EPSG:32123",
    "Oklahoma": "EPSG:32125",
    "Oregon": "EPSG:32127",
    "Pennsylvania": "EPSG:32129",
    "Rhode Island": "EPSG:32130",
    "South Carolina": "EPSG:32133",
    "South Dakota": "EPSG:32135",
    "Tennessee": "EPSG:32136",
    "Texas": "EPSG:32141",
    "Utah": "EPSG:32143",
    "Vermont": "EPSG:32145",
    "Virginia": "EPSG:32146",
    "Washington": "EPSG:32148",
    "West Virginia": "EPSG:32151",
    "Wisconsin": "EPSG:32153",
    "Wyoming": "EPSG:32155",
    "District of Columbia": "EPSG:26985",
}


# source for state names: https://gist.github.com/rogerallen/1583593
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}
    
# invert the dictionary
abbrev_to_us_state = dict(map(reversed, us_state_to_abbrev.items()))

def state_to_abbrev(name):
    return us_state_to_abbrev[name]
def abbrev_to_state(abbrev):
    return abbrev_to_us_state[abbrev]
def state_to_crs(name):
    return us_state_to_crs[name]
