def category_grouping(key, return_key_list=False):

	category_grouping_dict = {
		'Accounting, Tax Preparation, Bookkeeping, and Payroll Services' : 'Office',
		'Activities Related to Credit Intermediation' : 'Office',
		'Activities Related to Real Estate' : 'Office',
		'Administration of Economic Programs' : 'Office',
		'Administration of Housing Programs, Urban Planning, and Community Development' : 'Office',
		'Administration of Human Resource Programs' : 'Office',
		'Advertising, Public Relations, and Related Services' : 'Office',
		'Aerospace Product and Parts Manufacturing' : 'Manufacturing',
		'Agencies, Brokerages, and Other Insurance Related Activities' : 'Office',
		'Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures' : 'Office',
		'Agriculture, Construction, and Mining Machinery Manufacturing' : 'Manufacturing',
		'Alumina and Aluminum Production and Processing' : 'Manufacturing',
		'Amusement Parks and Arcades' : 'Recreation',
		'Apparel Accessories and Other Apparel Manufacturing' : 'Manufacturing',
		'Apparel, Piece Goods, and Notions Merchant Wholesalers' : 'Commercial',
		'Architectural and Structural Metals Manufacturing' : 'Manufacturing',
		'Architectural, Engineering, and Related Services' : 'Office',
		'Automobile Dealers' : 'Commercial',
		'Automotive Equipment Rental and Leasing' : 'Commercial',
		'Automotive Parts, Accessories, and Tire Stores' : 'Commercial',
		'Automotive Repair and Maintenance' : 'Commercial',
		'Bakeries and Tortilla Manufacturing' : 'Manufacturing',
		'Beer, Wine, and Liquor Stores' : 'Commercial',
		'Beverage Manufacturing' : 'Manufacturing',
		'Book Stores and News Dealers' : 'Commercial',
		'Building Equipment Contractors' : 'Office',
		'Building Finishing Contractors' : 'Office',
		'Building Material and Supplies Dealers' : 'Commercial',
		'Business Schools and Computer and Management Training' : 'Education/Child Care',
		'Business Support Services' : 'Office',
		'Business, Professional, Labor, Political, and Similar Organizations' : 'Office',
		'Cable and Other Subscription Programming' : 'Office',
		'Chemical and Allied Products Merchant Wholesalers' : 'Commercial',
		'Child Day Care Services' : 'Education/Child Care',
		'Civic and Social Organizations' : 'Office',
		'Clay Product and Refractory Manufacturing' : 'Manufacturing',
		'Clothing Stores' : 'Commercial',
		'Coating, Engraving, Heat Treating, and Allied Activities' : 'Manufacturing',
		'Colleges, Universities, and Professional Schools' : 'Education/Child Care',
		'Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance' : 'Manufacturing',
		'Commercial and Industrial Machinery and Equipment Rental and Leasing' : 'Commercial',
		'Community Food and Housing, and Emergency and Other Relief Services' : 'Medical',
		'Computer Systems Design and Related Services' : 'Commercial',
		'Consumer Goods Rental' : 'Commercial',
		'Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly' : 'Medical',
		'Converted Paper Product Manufacturing' : 'Manufacturing',
		'Couriers and Express Delivery Services' : 'Commercial',
		'Cut and Sew Apparel Manufacturing' : 'Manufacturing',
		'Data Processing, Hosting, and Related Services' : 'Manufacturing',
		'Death Care Services' : 'Commercial',
		'Deep Sea, Coastal, and Great Lakes Water Transportation' : 'Transit',
		'Department Stores' : 'Commercial',
		'Depository Credit Intermediation' : 'Office',
		'Direct Selling Establishments' : 'Commercial',
		'Drinking Places (Alcoholic Beverages)' : 'Restaurants and Bars',
		'Drugs and Druggists\' Sundries Merchant Wholesalers' : 'Manufacturing',
		'Drycleaning and Laundry Services' : 'Commercial',
		'Educational Support Services' : 'Education/Child Care',
		'Electric Power Generation, Transmission and Distribution' : 'Manufacturing',
		'Electrical Equipment Manufacturing' : 'Manufacturing',
		'Electronic Shopping and Mail-Order Houses' : 'Manufacturing',
		'Electronic and Precision Equipment Repair and Maintenance' : 'Commercial',
		'Electronics and Appliance Stores' : 'Commercial',
		'Elementary and Secondary Schools' : 'Education/Child Care',
		'Employment Services' : 'Commercial',
		'Executive, Legislative, and Other General Government Support' : 'Office',
		'Farm Product Raw Material Merchant Wholesalers' : 'Commercial',
		'Florists' : 'Commercial',
		'Footwear Manufacturing' : 'Manufacturing',
		'Foundation, Structure, and Building Exterior Contractors' : 'Manufacturing',
		'Freight Transportation Arrangement' : 'Manufacturing',
		'Furniture Stores' : 'Commercial',
		'Furniture and Home Furnishing Merchant Wholesalers' : 'Commercial',
		'Gambling Industries' : 'Recreation',
		'Gasoline Stations' : 'Gas Station',
		'General Freight Trucking' : 'Manufacturing',
		'General Medical and Surgical Hospitals' : 'Medical',
		'General Merchandise Stores, including Warehouse Clubs and Supercenters' : 'Commercial',
		'General Rental Centers' : 'Commercial',
		'Glass and Glass Product Manufacturing' : 'Manufacturing',
		'Grantmaking and Giving Services' : 'Office',
		'Greenhouse, Nursery, and Floriculture Production' : 'Commercial',
		'Grocery Stores' : 'Commercial',
		'Grocery and Related Product Merchant Wholesalers' : 'Commercial',
		'Hardware Manufacturing' : 'Manufacturing',
		'Hardware, and Plumbing and Heating Equipment and Supplies Merchant Wholesalers' : 'Commercial',
		'Health and Personal Care Stores' : 'Commercial',
		'Highway, Street, and Bridge Construction' : 'Manufacturing',
		'Home Furnishings Stores' : 'Commercial',
		'Home Health Care Services' : 'Medical',
		'Household Appliance Manufacturing' : 'Manufacturing',
		'Household Appliances and Electrical and Electronic Goods Merchant Wholesalers' : 'Commercial',
		'Household and Institutional Furniture and Kitchen Cabinet Manufacturing' : 'Manufacturing',
		'Independent Artists, Writers, and Performers' : 'Office',
		'Individual and Family Services' : 'Recreation',
		'Insurance Carriers' : 'Office',
		'Insurance and Employee Benefit Funds' : 'Office',
		'Interurban and Rural Bus Transportation' : 'Transit',
		'Investigation and Security Services' : 'Office',
		'Jewelry, Luggage, and Leather Goods Stores' : 'Commercial',
		'Junior Colleges' : 'Education/Child Care',
		'Justice, Public Order, and Safety Activities' : 'Office',
		'Lawn and Garden Equipment and Supplies Stores' : 'Commercial',
		'Legal Services' : 'Office',
		'Lessors of Real Estate' : 'Office',
		'Lumber and Other Construction Materials Merchant Wholesalers' : 'Commercial',
		'Machine Shops; Turned Product; and Screw, Nut, and Bolt Manufacturing' : 'Manufacturing',
		'Machinery, Equipment, and Supplies Merchant Wholesalers' : 'Commercial',
		'Management of Companies and Enterprises' : 'Office',
		'Management, Scientific, and Technical Consulting Services' : 'Office',
		'Medical Equipment and Supplies Manufacturing' : 'Manufacturing',
		'Medical and Diagnostic Laboratories' : 'Medical',
		'Metal and Mineral (except Petroleum) Merchant Wholesalers' : 'Commercial',
		'Miscellaneous Durable Goods Merchant Wholesalers' : 'Commercial',
		'Miscellaneous Nondurable Goods Merchant Wholesalers' : 'Commercial',
		'Motion Picture and Video Industries' : 'Recreation',
		'Motor Vehicle Manufacturing' : 'Manufacturing',
		'Motor Vehicle and Motor Vehicle Parts and Supplies Merchant Wholesalers' : 'Commercial',
		'Museums, Historical Sites, and Similar Institutions' : 'Recreation',
		'National Security and International Affairs' : 'Office',
		'Natural Gas Distribution' : 'Manufacturing',
		'Navigational, Measuring, Electromedical, and Control Instruments Manufacturing' : 'Manufacturing',
		'Newspaper, Periodical, Book, and Directory Publishers' : 'Office',
		'Nondepository Credit Intermediation' : 'Office',
		'Nursing Care Facilities (Skilled Nursing Facilities)' : 'Medical',
		'Nursing and Residential Care Facilities' : 'Medical',
		'Office Supplies, Stationery, and Gift Stores' : 'Commercial',
		'Offices of Dentists' : 'Medical',
		'Offices of Other Health Practitioners' : 'Medical',
		'Offices of Physicians' : 'Medical',
		'Offices of Real Estate Agents and Brokers' : 'Office',
		'Oil and Gas Extraction' : 'Manufacturing',
		'Other Ambulatory Health Care Services' : 'Medical',
		'Other Amusement and Recreation Industries' : 'Recreation',
		'Other Animal Production' : 'Manufacturing',
		'Other Fabricated Metal Product Manufacturing' : 'Manufacturing',
		'Other Financial Investment Activities' : 'Office',
		'Other Food Manufacturing' : 'Manufacturing',
		'Other Information Services' : 'Office',
		'Other Investment Pools and Funds' : 'Office',
		'Other Leather and Allied Product Manufacturing' : 'Manufacturing',
		'Other Miscellaneous Manufacturing' : 'Manufacturing',
		'Other Miscellaneous Store Retailers' : 'Commercial',
		'Other Motor Vehicle Dealers' : 'Commercial',
		'Other Nonmetallic Mineral Product Manufacturing' : 'Manufacturing',
		'Other Personal Services' : 'Commercial',
		'Other Professional, Scientific, and Technical Services' : 'Office',
		'Other Residential Care Facilities' : 'Medical',
		'Other Schools and Instruction' : 'Education/Child Care',
		'Other Specialty Trade Contractors' : 'Manufacturing',
		'Other Support Activities for Transportation' : 'Manufacturing',
		'Other Support Services' : 'Commercial',
		'Other Telecommunications' : 'Commercial',
		'Other Transit and Ground Passenger Transportation' : 'Transit',
		'Other Transportation Equipment Manufacturing' : 'Manufacturing',
		'Other Wood Product Manufacturing' : 'Manufacturing',
		'Outpatient Care Centers' : 'Medical',
		'Paint, Coating, and Adhesive Manufacturing' : 'Manufacturing',
		'Performing Arts Companies' : 'Recreation',
		'Personal Care Services' : 'Commercial',
		'Personal and Household Goods Repair and Maintenance' : 'Commercial',
		'Petroleum and Coal Products Manufacturing' : 'Manufacturing',
		'Petroleum and Petroleum Products Merchant Wholesalers' : 'Commercial',
		'Plastics Product Manufacturing' : 'Manufacturing',
		'Postal Service' : 'Commercial',
		'Printing and Related Support Activities' : 'Commercial',
		'Professional and Commercial Equipment and Supplies Merchant Wholesalers' : 'Commercial',
		'Promoters of Performing Arts, Sports, and Similar Events' : 'Office',
		'Psychiatric and Substance Abuse Hospitals' : 'Medical',
		'RV (Recreational Vehicle) Parks and Recreational Camps' : 'Recreation',
		'Radio and Television Broadcasting' : 'Office',
		'Rail Transportation' : 'Transit',
		'Religious Organizations' : 'Recreation',
		'Remediation and Other Waste Management Services' : 'Manufacturing',
		'Residential Building Construction' : 'Manufacturing',
		'Residential Intellectual and Developmental Disability, Mental Health, and Substance Abuse Facilities' : 'Medical',
		'Restaurants and Other Eating Places' : 'Restaurants and Bars',
		'Rooming and Boarding Houses, Dormitories, and Workers\' Camps' : 'Hotels',
		'Scenic and Sightseeing Transportation' : 'Recreation',
		'Scenic and Sightseeing Transportation, Land' : 'Recreation',
		'Scheduled Air Transportation' : 'Transit',
		'School and Employee Bus Transportation' : 'Transit',
		'Scientific Research and Development Services' : 'Office',
		'Securities and Commodity Contracts Intermediation and Brokerage' : 'Office',
		'Semiconductor and Other Electronic Component Manufacturing' : 'Manufacturing',
		'Services to Buildings and Dwellings' : 'Commercial',
		'Shoe Stores' : 'Commercial',
		'Social Advocacy Organizations' : 'Office',
		'Social Assistance' : 'Recreation',
		'Software Publishers' : 'Office',
		'Sound Recording Industries' : 'Office',
		'Special Food Services' : 'Commercial',
		'Specialized Design Services' : 'Commercial',
		'Specialized Freight Trucking' : 'Manufacturing',
		'Specialty (except Psychiatric and Substance Abuse) Hospitals' : 'Medical',
		'Specialty Food Stores' : 'Commercial',
		'Spectator Sports' : 'Recreation',
		'Sporting Goods, Hobby, and Musical Instrument Stores' : 'Commercial',
		'Steel Product Manufacturing from Purchased Steel' : 'Manufacturing',
		'Sugar and Confectionery Product Manufacturing' : 'Manufacturing',
		'Support Activities for Air Transportation' : 'Transit',
		'Support Activities for Crop Production' : 'Manufacturing',
		'Support Activities for Mining' : 'Manufacturing',
		'Support Activities for Road Transportation' : 'Transit',
		'Support Activities for Water Transportation' : 'Transit',
		'Taxi and Limousine Service' : 'Transit',
		'Technical and Trade Schools' : 'Education/Child Care',
		'Transit and Ground Passenger Transportation' : 'Transit',
		'Travel Arrangement and Reservation Services' : 'Commercial',
		'Traveler Accommodation' : 'Hotels',
		'Urban Transit Systems' : 'Transit',
		'Used Merchandise Stores' : 'Commercial',
		'Utility System Construction' : 'Manufacturing',
		'Vegetable and Melon Farming' : 'Manufacturing',
		'Ventilation, Heating, Air-Conditioning, and Commercial Refrigeration Equipment Manufacturing' : 'Manufacturing',
		'Warehousing and Storage' : 'Manufacturing',
		'Waste Collection' : 'Manufacturing',
		'Waste Management and Remediation Services' : 'Manufacturing',
		'Waste Treatment and Disposal' : 'Manufacturing',
		'Water Transportation' : 'Transit',
		'Wired and Wireless Telecommunications Carriers' : 'Commercial'}

	if return_key_list:
		return list(category_grouping_dict.keys())
	else:
		return category_grouping_dict[key]

